### ISSUE TITLE
a newline "open rstudio" is added, everytime the codespace is relaunched. 

### ISSUE THREAD

**Issue by kundeng** [MichaelAkridge-NOAA/Open-Science-Codespaces#2]

**Comment by MichaelAkridge-NOAA** [comment]
@kundeng thanks for using the images. 
I've updated with hotfix to address the issue. All new code spaces created will have the updated post_start code so it only adds the line once. 

If you still experience issues feel free to reopen or make a new issue. 

Cheers,
Michael
